/* Run with the bundled Playwright dependency; no @playwright/test installation. */
const { createRequire } = require('node:module');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const assert = require('node:assert/strict');
const {execFileSync} = require('node:child_process');
const requireBundled = createRequire(process.env.VOICE_PLAYWRIGHT_PACKAGE || path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json'));
const { chromium } = requireBundled('playwright');
const base = process.env.VOICE_QA_URL || 'http://127.0.0.1:5173/voice/';
const out = path.resolve(process.env.VOICE_QA_OUTPUT || 'output/playwright');
const profile = path.resolve('work/voice-qa-browser');
fs.mkdirSync(out,{recursive:true});
const archive = JSON.parse(fs.readFileSync('site/data/archive.json','utf8'));
const report = {url:base,started:new Date().toISOString(),checks:[],limitations:['Mobile viewport emulation is not physical iPhone/Safari proof.','Microphone fallback tests are simulated; real spoken recognition requires a person and microphone.','Synthetic speech invocation is checked, not perceptual pronunciation.']};
function check(name, value){assert(value,name);report.checks.push(name);}
function ownedProcesses(){
  const escaped=profile.replace(/'/g,"''");
  const command=`$voiceAll=@(Get-CimInstance Win32_Process); $voiceOwned=@($voiceAll | Where-Object { $_.Name -eq 'chrome.exe' -and $_.CommandLine -like '*${escaped}*' }); do { $voiceIds=@($voiceOwned.ProcessId); $voiceChildren=@($voiceAll | Where-Object { $_.ParentProcessId -in $voiceIds -and $_.ProcessId -notin $voiceIds }); $voiceOwned+= $voiceChildren } while ($voiceChildren.Count -gt 0); $voiceOwned | Select-Object ProcessId,ParentProcessId,CreationDate | ConvertTo-Json -Compress`;
  const text=execFileSync('powershell.exe',['-NoProfile','-Command',command],{encoding:'utf8'}).trim();
  return text ? JSON.parse(text) : [];
}
(async()=>{
 let context;
 try {
  context=await chromium.launchPersistentContext(profile,{channel:'chrome',headless:true,viewport:{width:1440,height:1000},deviceScaleFactor:1,locale:'el-GR'});
  report.ownedAtLaunch=ownedProcesses();
  const page=context.pages()[0]||await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base,{waitUntil:'networkidle'});
  await page.locator('.topic-card').first().waitFor();
  check('All topic cards load',await page.locator('.topic-card').count()===archive.topics.length);
  check('All memory cards load',await page.locator('.memory-card').count()===archive.memories.length);
  check('All detailed lessons load',await page.locator('.lesson').count()===archive.lessons.length);
  check('No audio download on initial render',await page.evaluate(()=>!performance.getEntriesByType('resource').some(r=>r.name.endsWith('.m4a'))));
  report.initial=await page.evaluate(()=>({navigationMs:performance.getEntriesByType('navigation')[0].duration,resourceBytes:performance.getEntriesByType('resource').reduce((s,r)=>s+r.transferSize,0),heapBytes:performance.memory?.usedJSHeapSize,viewport:[innerWidth,innerHeight]}));
  check('Desktop has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:path.join(out,'desktop.png')});
  await page.locator('.sun').click();
  check('Search sun focuses input',await page.locator('#search').evaluate(e=>e===document.activeElement));
  const query=archive.suggestions[0];
  const searchStart=Date.now();await page.locator('#search').fill(query);await page.locator('.result-item').first().waitFor();
  report.searchInteractionMs=Date.now()-searchStart;
  check('Live search finds source content',await page.locator('.result-item').count()>0);
  await page.screenshot({path:path.join(out,'search.png')});
  await page.locator('#search').fill('__missing_phrase_9317__');
  await page.waitForFunction(()=>document.querySelector('#result-count').textContent.startsWith('0 αποτελέσματα'));
  check('Empty search explains recovery',await page.locator('#results').innerText().then(t=>t.includes('Δοκίμασε')));
  await page.locator('#clear-search').click();
  const filter=page.locator('.filter').nth(1);await filter.click();
  check('Category filter narrows topics',await page.locator('.topic-card').count()<archive.topics.length);
  await page.locator('.filter').first().click();
  await page.locator('.topic-card [data-action="open"]').first().click();
  check('Topic reader shows source references',await page.locator('#reader .reader-refs button').count()>0);
  await page.keyboard.press('Escape');check('Dialog closes with Escape',!(await page.locator('#reader').evaluate(e=>e.open)));
  await page.locator('#audio').evaluate(e=>e.muted=true);
  await page.locator('.memory-card [data-action="play"]').first().click();
  await page.waitForFunction(()=>{const a=document.querySelector('#audio');return !a.paused&&a.currentTime>0&&a.readyState>=2;},null,{timeout:30000});
  const before=await page.locator('#audio').evaluate(e=>e.currentTime);
  await page.waitForTimeout(1300);
  const after=await page.locator('#audio').evaluate(e=>e.currentTime);
  check('Original audio advances from memory timestamp',before>=archive.memories[0].start-.5&&after>before+.5);
  await page.locator('#speed').selectOption('1.5');check('Playback speed works',await page.locator('#audio').evaluate(e=>e.playbackRate===1.5));
  await page.locator('#audio').evaluate((e,end)=>e.currentTime=end-.25,archive.memories[0].end);
  await page.waitForFunction(()=>document.querySelector('#audio').paused);
  check('Excerpt stops at its boundary',await page.locator('#now-subtitle').innerText().then(t=>t.includes('ολοκληρώθηκε')));
  await page.locator('#speed').selectOption('1');
  await page.locator('#chapter-select').selectOption('12');
  check('Final transcript chapter is available',await page.locator('.transcript-line').count()>0);
  await page.locator('#follow-audio').click();await page.locator('#audio').evaluate(e=>e.currentTime=1250);
  await page.waitForFunction(()=>document.querySelector('#chapter-select').value==='2');
  check('Transcript follows audio chapter',true);
  await page.locator('#follow-audio').click();
  await page.locator('.lesson summary').first().click();
  check('Detailed lesson expands',await page.locator('.lesson').first().evaluate(e=>e.open));
  await page.evaluate(()=>{window.__voiceSpeak=[];speechSynthesis.speak=u=>window.__voiceSpeak.push({text:u.text,lang:u.lang});});
  await page.locator('.lesson').first().locator('[data-action="speak"]').click();
  check('Synthetic reading invokes Greek speech',await page.evaluate(()=>window.__voiceSpeak.length>0&&window.__voiceSpeak[0].lang==='el-GR'));
  await page.locator('.lesson').first().locator('[data-action="stop-speech"]').click();
  await page.locator('#motion').click();check('Motion can be paused',await page.locator('body').evaluate(e=>e.classList.contains('no-motion')));
  await page.locator('#motion').click();
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  report.frames=await page.evaluate(()=>new Promise(resolve=>{const times=[];let prev=performance.now();function frame(now){times.push(now-prev);prev=now;if(times.length<121)requestAnimationFrame(frame);else{times.shift();times.sort((a,b)=>a-b);resolve({meanMs:times.reduce((a,b)=>a+b,0)/times.length,p95Ms:times[Math.floor(times.length*.95)],maxMs:Math.max(...times)});}}requestAnimationFrame(frame);}));
  await page.reload({waitUntil:'networkidle'});
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(250);
  check('Mobile has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:path.join(out,'mobile.png')});
  await page.evaluate(()=>window.scrollTo({top:document.querySelector('#galaxy').getBoundingClientRect().top+scrollY-80,behavior:'instant'}));await page.screenshot({path:path.join(out,'mobile-galaxy.png')});
  await page.evaluate(()=>window.scrollTo({top:document.querySelector('#library').getBoundingClientRect().top+scrollY-25,behavior:'instant'}));await page.screenshot({path:path.join(out,'mobile-library.png')});
  await page.locator('.topic-card [data-action="open"]').first().click();
  check('Mobile reader fits viewport',await page.locator('#reader').evaluate(e=>e.getBoundingClientRect().right<=innerWidth&&e.getBoundingClientRect().left>=0));
  await page.screenshot({path:path.join(out,'mobile-reader.png')});await page.locator('#close-reader').click();
  await page.setViewportSize({width:360,height:800});
  check('Small mobile has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.setViewportSize({width:820,height:1180});
  check('Tablet has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#audio').evaluate(e=>e.muted=true);
  await page.locator('.memory-card [data-action="play"]').first().click();
  await page.waitForFunction(()=>document.querySelector('#audio').readyState>=2);
  await page.locator('#audio').evaluate(e=>e.currentTime=3500);
  await page.waitForFunction(()=>document.querySelector('#audio').currentTime>=3667);
  check('Private interval is automatically skipped',true);
  await page.locator('#audio').evaluate(e=>e.pause());
  const sources=page.locator('#lesson-regulations-and-inspection');await sources.locator('summary').click();
  check('Learning notes link official sources',await sources.locator('.source-links a').count()===2);
  await page.locator('#search').fill('ΜΟΥΣΚΑΤ');await page.waitForFunction(()=>document.querySelector('#result-count').textContent.includes('ΜΟΥΣΚΑΤ'));
  check('Greek search ignores case and accents',await page.locator('.result-item').count()>0);
  await page.locator('#search').fill('RCBO');await page.waitForFunction(()=>document.querySelector('#result-count').textContent.includes('RCBO'));
  check('Technical abbreviation finds learning content',await page.locator('.result-item').count()>0);
  await page.locator('#search').fill('τηλεφωνική παρένθεση');await page.waitForFunction(()=>document.querySelector('#result-count').textContent.startsWith('0 αποτελέσματα'));
  check('Private marker is excluded from the searchable speech',true);
  const voice=await context.newPage();await voice.addInitScript(()=>{window.SpeechRecognition=class{start(){this.onstart?.();setTimeout(()=>{this.onresult?.({results:[[{transcript:'170'}]]});this.onend?.();},30);}stop(){this.onend?.();}};});await voice.goto(base);await voice.locator('.topic-card').first().waitFor();await voice.locator('#voice-search').click();await voice.locator('.result-item').first().waitFor();
  check('Recognized voice searches the common index (simulated)',await voice.locator('#search').inputValue()==='170');await voice.close();
  const unsupported=await context.newPage();await unsupported.addInitScript(()=>{window.SpeechRecognition=undefined;window.webkitSpeechRecognition=undefined;});await unsupported.goto(base);await unsupported.locator('.topic-card').first().waitFor();await unsupported.locator('#voice-search').click();
  check('Unsupported voice search has useful text fallback',await unsupported.locator('#voice-status').innerText().then(t=>t.includes('δεν υποστηρίζεται')));await unsupported.close();
  const denied=await context.newPage();await denied.addInitScript(()=>{window.SpeechRecognition=class{start(){setTimeout(()=>{this.onerror?.({error:'not-allowed'});this.onend?.();},20);}stop(){this.onend?.();}};});await denied.goto(base);await denied.locator('.topic-card').first().waitFor();await denied.locator('#voice-search').click();await denied.waitForFunction(()=>document.querySelector('#voice-status').textContent.includes('Δεν επιτράπηκε'));
  check('Microphone denial offers recovery (simulated)',true);await denied.close();
  const deep=await context.newPage();await deep.goto(`${base}?kind=memory&id=${archive.memories[0].id}`);await deep.locator('#reader[open]').waitFor();check('Direct memory link opens source story',await deep.locator('.reader-title').innerText()===archive.memories[0].title);await deep.close();
  report.pageErrors=errors;check('No uncaught page errors',errors.length===0);
  report.ok=true;
 } catch(error){report.ok=false;report.error=error.stack;process.exitCode=1;}
 finally{
  if(context)await context.close();
  const launch=Array.isArray(report.ownedAtLaunch)?report.ownedAtLaunch:[report.ownedAtLaunch].filter(Boolean);
  const ids=launch.map(p=>p.ProcessId);
  const remaining=ids.length?execFileSync('powershell.exe',['-NoProfile','-Command',`Get-CimInstance Win32_Process | Where-Object { $_.ProcessId -in @(${ids.join(',')}) } | Select-Object ProcessId,CreationDate | ConvertTo-Json -Compress`],{encoding:'utf8'}).trim():'';
  report.ownedAfterClose=remaining?JSON.parse(remaining):[];
  report.finished=new Date().toISOString();
  fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
 }
})();
